version: '3.8'
services:
  mqttbroker:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mqttbroker
    networks:
        - default
    expose:
        - "1883"
    ports:
        - "6503:1883"
    volumes :
            - /home/rajesh/Desktop/edge_cloud_exam/220340126002/Q5/mosq.conf:/mosquitto/config/mosquitto.conf
  subscriber:
    build: ./sub
    container_name: mqttsub
    hostname: subscriber
    depends_on:
        - mqttbroker